apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: newmarketelements-com-tls
spec:
  secretName: newmarketelements-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: newmarketelements.com
  dnsNames:
    - newmarketelements.com
    - www.newmarketelements.com